// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefUEykICOCamM-hpoTTELBN19Y9SJ-PQ',
    appId: '1:673115171607:ios:faea10cbf277bf249ca552',
    messagingSenderId: '673115171607',
    projectId: 'medical-app-1-794b8',
    storageBucket: 'medical-app-1-794b8.firebasestorage.app',
    iosBundleId: 'com.example.medicalStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9pER-CyYi6dut40wQuGgQzR4u36tYfcw',
    appId: '1:673115171607:web:8e6d1d2ad6f24e5f9ca552',
    messagingSenderId: '673115171607',
    projectId: 'medical-app-1-794b8',
    authDomain: 'medical-app-1-794b8.firebaseapp.com',
    storageBucket: 'medical-app-1-794b8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVP71o7d1PxFDvX4fDAqB3c2KdI0Pqcig',
    appId: '1:837257912647:web:2f6df2bcdc5991ee8b6c62',
    messagingSenderId: '837257912647',
    projectId: 'medical-app-731ef',
    authDomain: 'medical-app-731ef.firebaseapp.com',
    storageBucket: 'medical-app-731ef.firebasestorage.app',
    measurementId: 'G-EBS4JXX4BH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMYLoFBZcLXmasKdDTte57s6wWNmGIrcs',
    appId: '1:837257912647:ios:0cf638798eafbe368b6c62',
    messagingSenderId: '837257912647',
    projectId: 'medical-app-731ef',
    storageBucket: 'medical-app-731ef.firebasestorage.app',
    iosBundleId: 'com.example.medicalStoreApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_HIw1SpM4tXQrUvTpGE-pxRfmoAH1QVg',
    appId: '1:837257912647:android:0eb0895ef3c394c18b6c62',
    messagingSenderId: '837257912647',
    projectId: 'medical-app-731ef',
    storageBucket: 'medical-app-731ef.firebasestorage.app',
  );

}